spring.application.name=SQL Data Generator

spring.datasource.driver-class-name=org.postgresql.Driver

spring.autoconfigure.exclude=\
  org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
  org.springframework.boot.jdbc.autoconfigure.JdbcTemplateAutoConfiguration
